//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDB.Discover.Vault.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=(local)\\AUTODESKVAULT;Database=Load;Trusted_Connection=True;")]
        public string IDBConnectionString {
            get {
                return ((string)(this["IDBConnectionString"]));
            }
            set {
                this["IDBConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\TEMP\\BCP Package Directory")]
        public string ExportDirectory {
            get {
                return ((string)(this["ExportDirectory"]));
            }
            set {
                this["ExportDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=(local)\\AUTODESKVAULT;Database=TestVault;Trusted_Connection=True;")]
        public string VaultConnectionString {
            get {
                return ((string)(this["VaultConnectionString"]));
            }
            set {
                this["VaultConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KnowledgeVaultMaster")]
        public string KvmSqlDatabaseName {
            get {
                return ((string)(this["KvmSqlDatabaseName"]));
            }
            set {
                this["KvmSqlDatabaseName"] = value;
            }
        }
    }
}
