//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

namespace VaultBCPXSDSerialization
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/bom/2015-04-14")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/bom/2015-04-14", IsNullable = false)]
    public partial class BOMwrapper
    {

        private BOMComponentCollection bOMField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("component", typeof(BOMComponent), IsNullable = false)]
        public BOMComponentCollection BOM
        {
            get
            {
                return this.bOMField;
            }
            set
            {
                this.bOMField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/bom/2015-04-14")]
    public partial class BOMComponent
    {

        private instanceCollection instanceField;

        private occurrenceCollection occurrenceField;

        private BOMComponentItemToCompCollection itemToCompField;

        private BOMComponentPropertyCollection propertyField;

        private string bOMComponentIdField;

        private string fileIterationIdField;

        private string uIDField;

        private string nameField;

        private string componentTypeField;

        private string baseQtyField;

        private string structureNameField;

        private string baseUofMField;

        private string uofMIdField;

        private bool isInternalField;

        private bool isInternalFieldSpecified;

        private string contentSourceField;

        private bool isSubcomponentField;

        private bool isSubcomponentFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("instance")]
        public instanceCollection instance
        {
            get
            {
                return this.instanceField;
            }
            set
            {
                this.instanceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("occurrence")]
        public occurrenceCollection occurrence
        {
            get
            {
                return this.occurrenceField;
            }
            set
            {
                this.occurrenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("itemToComp")]
        public BOMComponentItemToCompCollection itemToComp
        {
            get
            {
                return this.itemToCompField;
            }
            set
            {
                this.itemToCompField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("property")]
        public BOMComponentPropertyCollection property
        {
            get
            {
                return this.propertyField;
            }
            set
            {
                this.propertyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BOMComponentId
        {
            get
            {
                return this.bOMComponentIdField;
            }
            set
            {
                this.bOMComponentIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FileIterationId
        {
            get
            {
                return this.fileIterationIdField;
            }
            set
            {
                this.fileIterationIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UID
        {
            get
            {
                return this.uIDField;
            }
            set
            {
                this.uIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ComponentType
        {
            get
            {
                return this.componentTypeField;
            }
            set
            {
                this.componentTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BaseQty
        {
            get
            {
                return this.baseQtyField;
            }
            set
            {
                this.baseQtyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StructureName
        {
            get
            {
                return this.structureNameField;
            }
            set
            {
                this.structureNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BaseUofM
        {
            get
            {
                return this.baseUofMField;
            }
            set
            {
                this.baseUofMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UofMId
        {
            get
            {
                return this.uofMIdField;
            }
            set
            {
                this.uofMIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isInternal
        {
            get
            {
                return this.isInternalField;
            }
            set
            {
                this.isInternalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isInternalSpecified
        {
            get
            {
                return this.isInternalFieldSpecified;
            }
            set
            {
                this.isInternalFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ContentSource
        {
            get
            {
                return this.contentSourceField;
            }
            set
            {
                this.contentSourceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isSubcomponent
        {
            get
            {
                return this.isSubcomponentField;
            }
            set
            {
                this.isSubcomponentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isSubcomponentSpecified
        {
            get
            {
                return this.isSubcomponentFieldSpecified;
            }
            set
            {
                this.isSubcomponentFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/bom/2015-04-14")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/bom/2015-04-14", IsNullable = false)]
    public partial class instance
    {

        private string bOMInstanceIdField;

        private string childFIDField;

        private string childUIDField;

        private string structureNameField;

        private string quantityField;

        private string qtyOverrideField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BOMInstanceId
        {
            get
            {
                return this.bOMInstanceIdField;
            }
            set
            {
                this.bOMInstanceIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ChildFID
        {
            get
            {
                return this.childFIDField;
            }
            set
            {
                this.childFIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ChildUID
        {
            get
            {
                return this.childUIDField;
            }
            set
            {
                this.childUIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StructureName
        {
            get
            {
                return this.structureNameField;
            }
            set
            {
                this.structureNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string QtyOverride
        {
            get
            {
                return this.qtyOverrideField;
            }
            set
            {
                this.qtyOverrideField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/bom/2015-04-14")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/bom/2015-04-14", IsNullable = false)]
    public partial class occurrence
    {

        private string bOMOccurrenceIdField;

        private string parentOccurrenceIdField;

        private string childFileIterationIDField;

        private string childUIDField;

        private string positionField;

        private string valueField;

        private string schemeTypeField;

        private string depthField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string BOMOccurrenceId
        {
            get
            {
                return this.bOMOccurrenceIdField;
            }
            set
            {
                this.bOMOccurrenceIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string ParentOccurrenceId
        {
            get
            {
                return this.parentOccurrenceIdField;
            }
            set
            {
                this.parentOccurrenceIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ChildFileIterationID
        {
            get
            {
                return this.childFileIterationIDField;
            }
            set
            {
                this.childFileIterationIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ChildUID
        {
            get
            {
                return this.childUIDField;
            }
            set
            {
                this.childUIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SchemeType
        {
            get
            {
                return this.schemeTypeField;
            }
            set
            {
                this.schemeTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Depth
        {
            get
            {
                return this.depthField;
            }
            set
            {
                this.depthField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/bom/2015-04-14")]
    public partial class BOMComponentItemToComp
    {

        private string itemIterationIDField;

        private string linkTypeField;

        private bool isSubcomponentField;

        private bool isSubcomponentFieldSpecified;

        private bool isManualField;

        private bool isManualFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemIterationID
        {
            get
            {
                return this.itemIterationIDField;
            }
            set
            {
                this.itemIterationIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LinkType
        {
            get
            {
                return this.linkTypeField;
            }
            set
            {
                this.linkTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isSubcomponent
        {
            get
            {
                return this.isSubcomponentField;
            }
            set
            {
                this.isSubcomponentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isSubcomponentSpecified
        {
            get
            {
                return this.isSubcomponentFieldSpecified;
            }
            set
            {
                this.isSubcomponentFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsManual
        {
            get
            {
                return this.isManualField;
            }
            set
            {
                this.isManualField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsManualSpecified
        {
            get
            {
                return this.isManualFieldSpecified;
            }
            set
            {
                this.isManualFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/bom/2015-04-14")]
    public partial class BOMComponentProperty
    {

        private string contentSourcePropertyMonikerField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ContentSourcePropertyMoniker
        {
            get
            {
                return this.contentSourcePropertyMonikerField;
            }
            set
            {
                this.contentSourcePropertyMonikerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/bom/2015-04-14")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/bom/2015-04-14", IsNullable = false)]
    public partial class BOM
    {

        private BOMComponentCollection componentField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("component")]
        public BOMComponentCollection component
        {
            get
            {
                return this.componentField;
            }
            set
            {
                this.componentField = value;
            }
        }
    }

}
