//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

namespace VaultBCPXSDSerialization
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/item/2015-04-14")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/item/2015-04-14", IsNullable = false)]
    public partial class Itemswrapper
    {

        private ItemMasterCollection itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ItemMaster", typeof(ItemswrapperItemsItemMaster), IsNullable = false)]
        public ItemMasterCollection Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/item/2015-04-14")]
    public partial class ItemswrapperItemsItemMaster
    {

        private ItemswrapperItemsItemMasterItemNumber itemNumberField;

        private ItemMasterRevCollection revField;

        private ItemRefDesMasterCollection itemRefDesMasterField;

        private string itemMasterIDField;

        private string categoryField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemNumber")]
        public ItemswrapperItemsItemMasterItemNumber ItemNumber
        {
            get
            {
                return this.itemNumberField;
            }
            set
            {
                this.itemNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Rev")]
        public ItemMasterRevCollection Rev
        {
            get
            {
                return this.revField;
            }
            set
            {
                this.revField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("itemRefDesMaster")]
        public ItemRefDesMasterCollection itemRefDesMaster
        {
            get
            {
                return this.itemRefDesMasterField;
            }
            set
            {
                this.itemRefDesMasterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemMasterID
        {
            get
            {
                return this.itemMasterIDField;
            }
            set
            {
                this.itemMasterIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/item/2015-04-14")]
    public partial class ItemswrapperItemsItemMasterItemNumber
    {

        private string itemNumberIDField;

        private string itemNumberField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemNumberID
        {
            get
            {
                return this.itemNumberIDField;
            }
            set
            {
                this.itemNumberIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemNumber
        {
            get
            {
                return this.itemNumberField;
            }
            set
            {
                this.itemNumberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/item/2015-04-14")]
    public partial class ItemswrapperItemsItemMasterRev
    {

        private IterationCollection iterationField;

        private string revIDField;

        private string defNameField;

        private string labelField;

        private float revOrderField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Iteration")]
        public IterationCollection Iteration
        {
            get
            {
                return this.iterationField;
            }
            set
            {
                this.iterationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RevID
        {
            get
            {
                return this.revIDField;
            }
            set
            {
                this.revIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DefName
        {
            get
            {
                return this.defNameField;
            }
            set
            {
                this.defNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Label
        {
            get
            {
                return this.labelField;
            }
            set
            {
                this.labelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float RevOrder
        {
            get
            {
                return this.revOrderField;
            }
            set
            {
                this.revOrderField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/item/2015-04-14")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/item/2015-04-14", IsNullable = false)]
    public partial class Iteration
    {

        private State stateField;

        private IterationUDPCollection uDPField;

        private IterationAttachmentCollection attachmentField;

        private IterationBomLinkCollection bomLinkField;

        private IterationDetailCollection detailField;

        private IterationDesignDocCollection designDocField;

        private IterationEffectivityCollection effectivityField;

        private string commentField;

        private string iterationIDField;

        private string iterationNumberField;

        private string createDateField;

        private string userGroupNameField;

        private string itemNumberIDField;

        private string itemTitleField;

        private string unitsField;

        private string descriptionField;

        private string bOMStructureField;

        private string partNumberField;

        private bool isReleasedField;

        private bool isObsoleteField;

        public Iteration()
        {
            this.isReleasedField = false;
            this.isObsoleteField = false;
        }

        /// <remarks/>
        public State State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UDP")]
        public IterationUDPCollection UDP
        {
            get
            {
                return this.uDPField;
            }
            set
            {
                this.uDPField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attachment")]
        public IterationAttachmentCollection Attachment
        {
            get
            {
                return this.attachmentField;
            }
            set
            {
                this.attachmentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("bomLink")]
        public IterationBomLinkCollection bomLink
        {
            get
            {
                return this.bomLinkField;
            }
            set
            {
                this.bomLinkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Detail")]
        public IterationDetailCollection Detail
        {
            get
            {
                return this.detailField;
            }
            set
            {
                this.detailField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DesignDoc")]
        public IterationDesignDocCollection DesignDoc
        {
            get
            {
                return this.designDocField;
            }
            set
            {
                this.designDocField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Effectivity")]
        public IterationEffectivityCollection Effectivity
        {
            get
            {
                return this.effectivityField;
            }
            set
            {
                this.effectivityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IterationID
        {
            get
            {
                return this.iterationIDField;
            }
            set
            {
                this.iterationIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string IterationNumber
        {
            get
            {
                return this.iterationNumberField;
            }
            set
            {
                this.iterationNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CreateDate
        {
            get
            {
                return this.createDateField;
            }
            set
            {
                this.createDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UserGroupName
        {
            get
            {
                return this.userGroupNameField;
            }
            set
            {
                this.userGroupNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemNumberID
        {
            get
            {
                return this.itemNumberIDField;
            }
            set
            {
                this.itemNumberIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemTitle
        {
            get
            {
                return this.itemTitleField;
            }
            set
            {
                this.itemTitleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Units
        {
            get
            {
                return this.unitsField;
            }
            set
            {
                this.unitsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BOMStructure
        {
            get
            {
                return this.bOMStructureField;
            }
            set
            {
                this.bOMStructureField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PartNumber
        {
            get
            {
                return this.partNumberField;
            }
            set
            {
                this.partNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsReleased
        {
            get
            {
                return this.isReleasedField;
            }
            set
            {
                this.isReleasedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsObsolete
        {
            get
            {
                return this.isObsoleteField;
            }
            set
            {
                this.isObsoleteField = value;
            }
        }
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/item/2015-04-14")]
    public partial class IterationUDP
    {

        private string nameField;

        private string valueField;

        private string value1Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value1
        {
            get
            {
                return this.value1Field;
            }
            set
            {
                this.value1Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/item/2015-04-14")]
    public partial class IterationAttachment
    {

        private string fileIterationIDField;

        private bool pinnedField;

        private bool pinnedFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FileIterationID
        {
            get
            {
                return this.fileIterationIDField;
            }
            set
            {
                this.fileIterationIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Pinned
        {
            get
            {
                return this.pinnedField;
            }
            set
            {
                this.pinnedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PinnedSpecified
        {
            get
            {
                return this.pinnedFieldSpecified;
            }
            set
            {
                this.pinnedFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/item/2015-04-14")]
    public partial class IterationBomLink
    {

        private IterationBomLinkBomLinkPropertyCollection bomLinkPropertyField;

        private string itemBOMLinkIDField;

        private float quantityField;

        private bool quantityFieldSpecified;

        private string uofMIDField;

        private string bOMOrderField;

        private string linkTypeField;

        private string childItemMasterIDField;

        private string childFileIterationIDField;

        private string childUIDField;

        private int instanceCountField;

        private bool instanceCountFieldSpecified;

        private float unitSizeField;

        private bool unitSizeFieldSpecified;

        private bool cADField;

        private bool cADFieldSpecified;

        private string positionNumberField;

        private int groupByField;

        private bool groupByFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("bomLinkProperty")]
        public IterationBomLinkBomLinkPropertyCollection bomLinkProperty
        {
            get
            {
                return this.bomLinkPropertyField;
            }
            set
            {
                this.bomLinkPropertyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemBOMLinkID
        {
            get
            {
                return this.itemBOMLinkIDField;
            }
            set
            {
                this.itemBOMLinkIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantitySpecified
        {
            get
            {
                return this.quantityFieldSpecified;
            }
            set
            {
                this.quantityFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UofMID
        {
            get
            {
                return this.uofMIDField;
            }
            set
            {
                this.uofMIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string BOMOrder
        {
            get
            {
                return this.bOMOrderField;
            }
            set
            {
                this.bOMOrderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LinkType
        {
            get
            {
                return this.linkTypeField;
            }
            set
            {
                this.linkTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ChildItemMasterID
        {
            get
            {
                return this.childItemMasterIDField;
            }
            set
            {
                this.childItemMasterIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ChildFileIterationID
        {
            get
            {
                return this.childFileIterationIDField;
            }
            set
            {
                this.childFileIterationIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ChildUID
        {
            get
            {
                return this.childUIDField;
            }
            set
            {
                this.childUIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int InstanceCount
        {
            get
            {
                return this.instanceCountField;
            }
            set
            {
                this.instanceCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InstanceCountSpecified
        {
            get
            {
                return this.instanceCountFieldSpecified;
            }
            set
            {
                this.instanceCountFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float UnitSize
        {
            get
            {
                return this.unitSizeField;
            }
            set
            {
                this.unitSizeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UnitSizeSpecified
        {
            get
            {
                return this.unitSizeFieldSpecified;
            }
            set
            {
                this.unitSizeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool CAD
        {
            get
            {
                return this.cADField;
            }
            set
            {
                this.cADField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CADSpecified
        {
            get
            {
                return this.cADFieldSpecified;
            }
            set
            {
                this.cADFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PositionNumber
        {
            get
            {
                return this.positionNumberField;
            }
            set
            {
                this.positionNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int GroupBy
        {
            get
            {
                return this.groupByField;
            }
            set
            {
                this.groupByField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GroupBySpecified
        {
            get
            {
                return this.groupByFieldSpecified;
            }
            set
            {
                this.groupByFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/item/2015-04-14")]
    public partial class IterationBomLinkBomLinkProperty
    {

        private string friendlyNameField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FriendlyName
        {
            get
            {
                return this.friendlyNameField;
            }
            set
            {
                this.friendlyNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/item/2015-04-14")]
    public partial class IterationDetail
    {

        private string occurrenceIdField;

        private string parentOccurrenceIdField;

        private string parentItemMasterIdField;

        private string childFileIterationIDField;

        private string childUIDField;

        private string positionField;

        private string detailIdField;

        private string schemeIdField;

        private bool isStructuredField;

        private bool isStructuredFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OccurrenceId
        {
            get
            {
                return this.occurrenceIdField;
            }
            set
            {
                this.occurrenceIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ParentOccurrenceId
        {
            get
            {
                return this.parentOccurrenceIdField;
            }
            set
            {
                this.parentOccurrenceIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ParentItemMasterId
        {
            get
            {
                return this.parentItemMasterIdField;
            }
            set
            {
                this.parentItemMasterIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ChildFileIterationID
        {
            get
            {
                return this.childFileIterationIDField;
            }
            set
            {
                this.childFileIterationIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ChildUID
        {
            get
            {
                return this.childUIDField;
            }
            set
            {
                this.childUIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DetailId
        {
            get
            {
                return this.detailIdField;
            }
            set
            {
                this.detailIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string SchemeId
        {
            get
            {
                return this.schemeIdField;
            }
            set
            {
                this.schemeIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsStructured
        {
            get
            {
                return this.isStructuredField;
            }
            set
            {
                this.isStructuredField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsStructuredSpecified
        {
            get
            {
                return this.isStructuredFieldSpecified;
            }
            set
            {
                this.isStructuredFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/item/2015-04-14")]
    public partial class IterationDesignDoc
    {

        private string fileIterationIDField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FileIterationID
        {
            get
            {
                return this.fileIterationIDField;
            }
            set
            {
                this.fileIterationIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/item/2015-04-14")]
    public partial class IterationEffectivity
    {

        private string effStartField;

        private string effEndField;

        private string effectivityField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EffStart
        {
            get
            {
                return this.effStartField;
            }
            set
            {
                this.effStartField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EffEnd
        {
            get
            {
                return this.effEndField;
            }
            set
            {
                this.effEndField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string Effectivity
        {
            get
            {
                return this.effectivityField;
            }
            set
            {
                this.effectivityField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/item/2015-04-14")]
    public partial class ItemswrapperItemsItemMasterItemRefDesMaster
    {

        private ItemRefDesIterationCollection itemRefDesIterationField;

        private string itemRefDesMasterIDField;

        private string locationField;

        private string installationField;

        private string tagField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("itemRefDesIteration")]
        public ItemRefDesIterationCollection itemRefDesIteration
        {
            get
            {
                return this.itemRefDesIterationField;
            }
            set
            {
                this.itemRefDesIterationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemRefDesMasterID
        {
            get
            {
                return this.itemRefDesMasterIDField;
            }
            set
            {
                this.itemRefDesMasterIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Installation
        {
            get
            {
                return this.installationField;
            }
            set
            {
                this.installationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Tag
        {
            get
            {
                return this.tagField;
            }
            set
            {
                this.tagField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/item/2015-04-14")]
    public partial class ItemswrapperItemsItemMasterItemRefDesMasterItemRefDesIteration
    {

        private ItemRefDesInstanceCollection itemRefDesInstanceField;

        private ItemRefDesIterationPropCollection propField;

        private string itemRefDesIterationIDField;

        private string iterationNumberField;

        private string commentField;

        private string createDateField;

        private string createUserIDField;

        private bool activeField;

        private bool activeFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("itemRefDesInstance")]
        public ItemRefDesInstanceCollection itemRefDesInstance
        {
            get
            {
                return this.itemRefDesInstanceField;
            }
            set
            {
                this.itemRefDesInstanceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("prop")]
        public ItemRefDesIterationPropCollection prop
        {
            get
            {
                return this.propField;
            }
            set
            {
                this.propField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemRefDesIterationID
        {
            get
            {
                return this.itemRefDesIterationIDField;
            }
            set
            {
                this.itemRefDesIterationIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string IterationNumber
        {
            get
            {
                return this.iterationNumberField;
            }
            set
            {
                this.iterationNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CreateDate
        {
            get
            {
                return this.createDateField;
            }
            set
            {
                this.createDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CreateUserID
        {
            get
            {
                return this.createUserIDField;
            }
            set
            {
                this.createUserIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Active
        {
            get
            {
                return this.activeField;
            }
            set
            {
                this.activeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActiveSpecified
        {
            get
            {
                return this.activeFieldSpecified;
            }
            set
            {
                this.activeFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/item/2015-04-14")]
    public partial class ItemswrapperItemsItemMasterItemRefDesMasterItemRefDesIterationItemRefDesInstance
    {

        private string itemRefDesInstanceIDField;

        private float quantityField;

        private bool quantityFieldSpecified;

        private string createDateField;

        private string createUserIDField;

        private string fromIdField;

        private string toIdField;

        private bool activeField;

        private bool activeFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemRefDesInstanceID
        {
            get
            {
                return this.itemRefDesInstanceIDField;
            }
            set
            {
                this.itemRefDesInstanceIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantitySpecified
        {
            get
            {
                return this.quantityFieldSpecified;
            }
            set
            {
                this.quantityFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CreateDate
        {
            get
            {
                return this.createDateField;
            }
            set
            {
                this.createDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CreateUserID
        {
            get
            {
                return this.createUserIDField;
            }
            set
            {
                this.createUserIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FromId
        {
            get
            {
                return this.fromIdField;
            }
            set
            {
                this.fromIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ToId
        {
            get
            {
                return this.toIdField;
            }
            set
            {
                this.toIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Active
        {
            get
            {
                return this.activeField;
            }
            set
            {
                this.activeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActiveSpecified
        {
            get
            {
                return this.activeFieldSpecified;
            }
            set
            {
                this.activeFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/item/2015-04-14")]
    public partial class ItemswrapperItemsItemMasterItemRefDesMasterItemRefDesIterationProp
    {

        private string friendlyNameField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FriendlyName
        {
            get
            {
                return this.friendlyNameField;
            }
            set
            {
                this.friendlyNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

}
