//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

namespace VaultBCPXSDSerialization
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14", IsNullable = false)]
    public partial class Vault
    {

        private VaultStatistics statisticsField;

        private VaultSecurity securityField;

        private VaultBehaviors behaviorsField;

        private VaultRoot rootField;

        private string sourceIdField;

        /// <remarks/>
        public VaultStatistics Statistics
        {
            get
            {
                return this.statisticsField;
            }
            set
            {
                this.statisticsField = value;
            }
        }

        /// <remarks/>
        public VaultSecurity Security
        {
            get
            {
                return this.securityField;
            }
            set
            {
                this.securityField = value;
            }
        }

        /// <remarks/>
        public VaultBehaviors Behaviors
        {
            get
            {
                return this.behaviorsField;
            }
            set
            {
                this.behaviorsField = value;
            }
        }

        /// <remarks/>
        public VaultRoot Root
        {
            get
            {
                return this.rootField;
            }
            set
            {
                this.rootField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sourceId
        {
            get
            {
                return this.sourceIdField;
            }
            set
            {
                this.sourceIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14")]
    public partial class VaultStatistics
    {

        private string totalFoldersField;

        private string totalFilesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string TotalFolders
        {
            get
            {
                return this.totalFoldersField;
            }
            set
            {
                this.totalFoldersField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string TotalFiles
        {
            get
            {
                return this.totalFilesField;
            }
            set
            {
                this.totalFilesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14")]
    public abstract partial class SecurityPrincipal
    {

        private SecurityPrincipalInRole[] inRoleField;

        private SecurityPrincipalInGroup[] inGroupField;

        private string nameField;

        private SecurityPrincipalAuthentication authenticationField;

        private bool activeField;

        private SecurityPrincipalAccess accessField;

        public SecurityPrincipal()
        {
            this.activeField = true;
            this.accessField = SecurityPrincipalAccess.ThisVault;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InRole")]
        public SecurityPrincipalInRole[] InRole
        {
            get
            {
                return this.inRoleField;
            }
            set
            {
                this.inRoleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InGroup")]
        public SecurityPrincipalInGroup[] InGroup
        {
            get
            {
                return this.inGroupField;
            }
            set
            {
                this.inGroupField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SecurityPrincipalAuthentication Authentication
        {
            get
            {
                return this.authenticationField;
            }
            set
            {
                this.authenticationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Active
        {
            get
            {
                return this.activeField;
            }
            set
            {
                this.activeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(SecurityPrincipalAccess.ThisVault)]
        public SecurityPrincipalAccess Access
        {
            get
            {
                return this.accessField;
            }
            set
            {
                this.accessField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14")]
    public partial class SecurityPrincipalInRole
    {

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14")]
    public partial class SecurityPrincipalInGroup
    {

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14")]
    public enum SecurityPrincipalAuthentication
    {

        /// <remarks/>
        Vault,

        /// <remarks/>
        Windows,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14")]
    public enum SecurityPrincipalAccess
    {

        /// <remarks/>
        NoVaults,

        /// <remarks/>
        AllVaults,

        /// <remarks/>
        ThisVault,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14")]
    public partial class VaultSecurity
    {

        private VaultSecurityRole[] roleField;

        private VaultSecurityGroup[] groupField;

        private VaultSecurityUser[] userField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Role")]
        public VaultSecurityRole[] Role
        {
            get
            {
                return this.roleField;
            }
            set
            {
                this.roleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Group")]
        public VaultSecurityGroup[] Group
        {
            get
            {
                return this.groupField;
            }
            set
            {
                this.groupField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("User")]
        public VaultSecurityUser[] User
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14")]
    public partial class VaultSecurityRole
    {

        private VaultSecurityRolePermission[] permissionField;

        private string nameField;

        private string descriptionField;

        public VaultSecurityRole()
        {
            this.descriptionField = "";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Permission")]
        public VaultSecurityRolePermission[] Permission
        {
            get
            {
                return this.permissionField;
            }
            set
            {
                this.permissionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14")]
    public partial class VaultSecurityRolePermission
    {

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14")]
    public partial class VaultSecurityGroup : SecurityPrincipal
    {

        private string emailField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14")]
    public partial class VaultSecurityUser : SecurityPrincipal
    {

        private string passwordField;

        private string firstNameField;

        private string lastNameField;

        private string emailField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FirstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14")]
    public partial class VaultBehaviors
    {

        private VaultBehaviorsCategoryDefinition[] categoryDefinitionField;

        private VaultBehaviorsPropertyDefinition[] propertyDefinitionField;

        private VaultBehaviorsLifecycleDefinition[] lifecycleDefinitionField;

        private VaultBehaviorsRevisionSequence[] revisionSequenceField;

        private VaultBehaviorsRevisionDefinition[] revisionDefinitionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CategoryDefinition")]
        public VaultBehaviorsCategoryDefinition[] CategoryDefinition
        {
            get
            {
                return this.categoryDefinitionField;
            }
            set
            {
                this.categoryDefinitionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PropertyDefinition")]
        public VaultBehaviorsPropertyDefinition[] PropertyDefinition
        {
            get
            {
                return this.propertyDefinitionField;
            }
            set
            {
                this.propertyDefinitionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LifecycleDefinition")]
        public VaultBehaviorsLifecycleDefinition[] LifecycleDefinition
        {
            get
            {
                return this.lifecycleDefinitionField;
            }
            set
            {
                this.lifecycleDefinitionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RevisionSequence")]
        public VaultBehaviorsRevisionSequence[] RevisionSequence
        {
            get
            {
                return this.revisionSequenceField;
            }
            set
            {
                this.revisionSequenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RevisionDefinition")]
        public VaultBehaviorsRevisionDefinition[] RevisionDefinition
        {
            get
            {
                return this.revisionDefinitionField;
            }
            set
            {
                this.revisionDefinitionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14")]
    public partial class VaultBehaviorsCategoryDefinition
    {

        private string nameField;

        private string descriptionField;

        private Class classField;

        private string colorField;

        private AssignmentType assignmentTypeField;

        public VaultBehaviorsCategoryDefinition()
        {
            this.colorField = "-1";
            this.assignmentTypeField = AssignmentType.Enabled;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Class Class
        {
            get
            {
                return this.classField;
            }
            set
            {
                this.classField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        [System.ComponentModel.DefaultValueAttribute("-1")]
        public string Color
        {
            get
            {
                return this.colorField;
            }
            set
            {
                this.colorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(AssignmentType.Enabled)]
        public AssignmentType AssignmentType
        {
            get
            {
                return this.assignmentTypeField;
            }
            set
            {
                this.assignmentTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14")]
    public enum Class
    {

        /// <remarks/>
        File,

        /// <remarks/>
        Folder,

        /// <remarks/>
        Item,

        /// <remarks/>
        CustomEntity,

        /// <remarks/>
        ItemRefDesMaster,

        /// <remarks/>
        Link,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14")]
    public enum AssignmentType
    {

        /// <remarks/>
        Enabled,

        /// <remarks/>
        Disabled,

        /// <remarks/>
        Default,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14")]
    public partial class VaultBehaviorsPropertyDefinition
    {

        private Assignment[] assignmentField;

        private object defaultField;

        private object[] listField;

        private string nameField;

        private VaultBehaviorsPropertyDefinitionType typeField;

        private bool activeField;

        private bool basicSearchField;

        public VaultBehaviorsPropertyDefinition()
        {
            this.typeField = VaultBehaviorsPropertyDefinitionType.String;
            this.activeField = true;
            this.basicSearchField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Assignment")]
        public Assignment[] Assignment
        {
            get
            {
                return this.assignmentField;
            }
            set
            {
                this.assignmentField = value;
            }
        }

        /// <remarks/>
        public object Default
        {
            get
            {
                return this.defaultField;
            }
            set
            {
                this.defaultField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("List")]
        public object[] List
        {
            get
            {
                return this.listField;
            }
            set
            {
                this.listField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(VaultBehaviorsPropertyDefinitionType.String)]
        public VaultBehaviorsPropertyDefinitionType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Active
        {
            get
            {
                return this.activeField;
            }
            set
            {
                this.activeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool BasicSearch
        {
            get
            {
                return this.basicSearchField;
            }
            set
            {
                this.basicSearchField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14", IsNullable = false)]
    public partial class Assignment
    {

        private AssignmentCategory[] categoryField;

        private Class classField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Category")]
        public AssignmentCategory[] Category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Class Class
        {
            get
            {
                return this.classField;
            }
            set
            {
                this.classField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14")]
    public partial class AssignmentCategory
    {

        private string nameField;

        private AssignmentType assignmentTypeField;

        public AssignmentCategory()
        {
            this.assignmentTypeField = AssignmentType.Enabled;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(AssignmentType.Enabled)]
        public AssignmentType AssignmentType
        {
            get
            {
                return this.assignmentTypeField;
            }
            set
            {
                this.assignmentTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14")]
    public enum VaultBehaviorsPropertyDefinitionType
    {

        /// <remarks/>
        String,

        /// <remarks/>
        Numeric,

        /// <remarks/>
        DateTime,

        /// <remarks/>
        Bool,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14")]
    public partial class VaultBehaviorsLifecycleDefinition
    {

        private Assignment[] assignmentField;

        private VaultBehaviorsLifecycleDefinitionState[] stateField;

        private string nameField;

        private string descriptionField;

        private VaultBehaviorsLifecycleDefinitionACLbehavior aCLbehaviorField;

        public VaultBehaviorsLifecycleDefinition()
        {
            this.aCLbehaviorField = VaultBehaviorsLifecycleDefinitionACLbehavior.Override;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Assignment")]
        public Assignment[] Assignment
        {
            get
            {
                return this.assignmentField;
            }
            set
            {
                this.assignmentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("State")]
        public VaultBehaviorsLifecycleDefinitionState[] State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(VaultBehaviorsLifecycleDefinitionACLbehavior.Override)]
        public VaultBehaviorsLifecycleDefinitionACLbehavior ACLbehavior
        {
            get
            {
                return this.aCLbehaviorField;
            }
            set
            {
                this.aCLbehaviorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14")]
    public partial class VaultBehaviorsLifecycleDefinitionState
    {

        private ACLACE[] aCLField;

        private string nameField;

        private string descriptionField;

        private bool isReleasedField;

        private bool isObsoleteField;

        private bool isObsoleteFieldSpecified;

        private bool isDefaultField;

        private VaultBehaviorsLifecycleDefinitionStatePurgeRestrictions purgeRestrictionsField;

        public VaultBehaviorsLifecycleDefinitionState()
        {
            this.isDefaultField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ACE", IsNullable = false)]
        public ACLACE[] ACL
        {
            get
            {
                return this.aCLField;
            }
            set
            {
                this.aCLField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsReleased
        {
            get
            {
                return this.isReleasedField;
            }
            set
            {
                this.isReleasedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsObsolete
        {
            get
            {
                return this.isObsoleteField;
            }
            set
            {
                this.isObsoleteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsObsoleteSpecified
        {
            get
            {
                return this.isObsoleteFieldSpecified;
            }
            set
            {
                this.isObsoleteFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsDefault
        {
            get
            {
                return this.isDefaultField;
            }
            set
            {
                this.isDefaultField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public VaultBehaviorsLifecycleDefinitionStatePurgeRestrictions PurgeRestrictions
        {
            get
            {
                return this.purgeRestrictionsField;
            }
            set
            {
                this.purgeRestrictionsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14")]
    public partial class ACLACE
    {

        private string userField;

        private bool readField;

        private bool readFieldSpecified;

        private bool writeField;

        private bool writeFieldSpecified;

        private bool deleteField;

        private bool deleteFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string User
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Read
        {
            get
            {
                return this.readField;
            }
            set
            {
                this.readField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReadSpecified
        {
            get
            {
                return this.readFieldSpecified;
            }
            set
            {
                this.readFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Write
        {
            get
            {
                return this.writeField;
            }
            set
            {
                this.writeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WriteSpecified
        {
            get
            {
                return this.writeFieldSpecified;
            }
            set
            {
                this.writeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Delete
        {
            get
            {
                return this.deleteField;
            }
            set
            {
                this.deleteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeleteSpecified
        {
            get
            {
                return this.deleteFieldSpecified;
            }
            set
            {
                this.deleteFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14")]
    public enum VaultBehaviorsLifecycleDefinitionStatePurgeRestrictions
    {

        /// <remarks/>
        All,

        /// <remarks/>
        FirstAndLast,

        /// <remarks/>
        Last,

        /// <remarks/>
        None,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14")]
    public enum VaultBehaviorsLifecycleDefinitionACLbehavior
    {

        /// <remarks/>
        Override,

        /// <remarks/>
        Combined,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14")]
    public partial class VaultBehaviorsRevisionSequence
    {

        private string[] labelField;

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Label")]
        public string[] Label
        {
            get
            {
                return this.labelField;
            }
            set
            {
                this.labelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14")]
    public partial class VaultBehaviorsRevisionDefinition
    {

        private Assignment[] assignmentField;

        private string nameField;

        private string descriptionField;

        private VaultBehaviorsRevisionDefinitionDelimiter delimiterField;

        private string primarySequenceField;

        private string secondarySequenceField;

        private string tertiarySequenceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Assignment")]
        public Assignment[] Assignment
        {
            get
            {
                return this.assignmentField;
            }
            set
            {
                this.assignmentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public VaultBehaviorsRevisionDefinitionDelimiter Delimiter
        {
            get
            {
                return this.delimiterField;
            }
            set
            {
                this.delimiterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PrimarySequence
        {
            get
            {
                return this.primarySequenceField;
            }
            set
            {
                this.primarySequenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SecondarySequence
        {
            get
            {
                return this.secondarySequenceField;
            }
            set
            {
                this.secondarySequenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TertiarySequence
        {
            get
            {
                return this.tertiarySequenceField;
            }
            set
            {
                this.tertiarySequenceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14")]
    public enum VaultBehaviorsRevisionDefinitionDelimiter
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(".")]
        Item,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(",")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(";")]
        Item2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":")]
        Item3,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("-")]
        Item4,

        /// <remarks/>
        _,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("\\")]
        Item5,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/")]
        Item6,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("\"")]
        Item7,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("\'")]
        Item8,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14")]
    public partial class VaultRoot
    {

        private ACLACE[] aCLField;

        private FolderCollection folderField;

        private FileCollection fileField;

        private Link[] linkField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ACE", IsNullable = false)]
        public ACLACE[] ACL
        {
            get
            {
                return this.aCLField;
            }
            set
            {
                this.aCLField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Folder")]
        public FolderCollection Folder
        {
            get
            {
                return this.folderField;
            }
            set
            {
                this.folderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("File")]
        public FileCollection File
        {
            get
            {
                return this.fileField;
            }
            set
            {
                this.fileField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Link")]
        public Link[] Link
        {
            get
            {
                return this.linkField;
            }
            set
            {
                this.linkField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14", IsNullable = false)]
    public partial class Folder
    {

        private Created createdField;

        private ACLACE[] aCLField;

        private State stateField;

        private UDPCollection uDPField;

        private FolderCollection folder1Field;

        private FileCollection fileField;

        private Link[] linkField;

        private string nameField;

        private bool isLibraryField;

        private string categoryField;

        private string idField;

        public Folder()
        {
            this.isLibraryField = false;
        }

        /// <remarks/>
        public Created Created
        {
            get
            {
                return this.createdField;
            }
            set
            {
                this.createdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ACE", IsNullable = false)]
        public ACLACE[] ACL
        {
            get
            {
                return this.aCLField;
            }
            set
            {
                this.aCLField = value;
            }
        }

        /// <remarks/>
        public State State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UDP")]
        public UDPCollection UDP
        {
            get
            {
                return this.uDPField;
            }
            set
            {
                this.uDPField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Folder")]
        public FolderCollection Folder1
        {
            get
            {
                return this.folder1Field;
            }
            set
            {
                this.folder1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("File")]
        public FileCollection File
        {
            get
            {
                return this.fileField;
            }
            set
            {
                this.fileField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Link")]
        public Link[] Link
        {
            get
            {
                return this.linkField;
            }
            set
            {
                this.linkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsLibrary
        {
            get
            {
                return this.isLibraryField;
            }
            set
            {
                this.isLibraryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14", IsNullable = false)]
    public partial class Created
    {

        private string userField;

        private System.DateTime dateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string User
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14", IsNullable = false)]
    public partial class UDP
    {

        private string nameField;

        private string[] textField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14", IsNullable = false)]
    public partial class File
    {

        private ACLACE[] aCLField;

        private FileRevisionCollection revisionField;

        private string nameField;

        private FileClassification classificationField;

        private string hiddenField;

        private string categoryField;

        private FileACLbehavior aCLbehaviorField;

        public File()
        {
            this.classificationField = FileClassification.None;
            this.hiddenField = "false";
            this.aCLbehaviorField = FileACLbehavior.Override;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ACE", IsNullable = false)]
        public ACLACE[] ACL
        {
            get
            {
                return this.aCLField;
            }
            set
            {
                this.aCLField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Revision")]
        public FileRevisionCollection Revision
        {
            get
            {
                return this.revisionField;
            }
            set
            {
                this.revisionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(FileClassification.None)]
        public FileClassification Classification
        {
            get
            {
                return this.classificationField;
            }
            set
            {
                this.classificationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("false")]
        public string Hidden
        {
            get
            {
                return this.hiddenField;
            }
            set
            {
                this.hiddenField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(FileACLbehavior.Override)]
        public FileACLbehavior ACLbehavior
        {
            get
            {
                return this.aCLbehaviorField;
            }
            set
            {
                this.aCLbehaviorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14")]
    public partial class FileRevision
    {

        private object[] itemsField;

        private string definitionField;

        private string labelField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Iteration", typeof(FileRevisionIteration))]
        [System.Xml.Serialization.XmlElementAttribute("IterationRef", typeof(FileRevisionIterationRef))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Definition
        {
            get
            {
                return this.definitionField;
            }
            set
            {
                this.definitionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Label
        {
            get
            {
                return this.labelField;
            }
            set
            {
                this.labelField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14")]
    public partial class FileRevisionIteration
    {

        private Created createdField;

        private State stateField;

        private UDPCollection uDPField;

        private FileRevisionIterationAssociationCollection associationField;

        private string commentField;

        private System.DateTime modifiedField;

        private string localPathField;

        private string idField;

        private string contentSourceField;

        /// <remarks/>
        public Created Created
        {
            get
            {
                return this.createdField;
            }
            set
            {
                this.createdField = value;
            }
        }

        /// <remarks/>
        public State State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UDP")]
        public UDPCollection UDP
        {
            get
            {
                return this.uDPField;
            }
            set
            {
                this.uDPField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Association")]
        public FileRevisionIterationAssociationCollection Association
        {
            get
            {
                return this.associationField;
            }
            set
            {
                this.associationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime Modified
        {
            get
            {
                return this.modifiedField;
            }
            set
            {
                this.modifiedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LocalPath
        {
            get
            {
                return this.localPathField;
            }
            set
            {
                this.localPathField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ContentSource
        {
            get
            {
                return this.contentSourceField;
            }
            set
            {
                this.contentSourceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14")]
    public partial class FileRevisionIterationAssociation
    {

        private string childIdField;

        private FileRevisionIterationAssociationType typeField;

        private string sourceField;

        private string refIdField;

        private bool needsResolutionField;

        public FileRevisionIterationAssociation()
        {
            this.typeField = FileRevisionIterationAssociationType.Dependency;
            this.needsResolutionField = true;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "IDREF")]
        public string ChildId
        {
            get
            {
                return this.childIdField;
            }
            set
            {
                this.childIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(FileRevisionIterationAssociationType.Dependency)]
        public FileRevisionIterationAssociationType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RefId
        {
            get
            {
                return this.refIdField;
            }
            set
            {
                this.refIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool NeedsResolution
        {
            get
            {
                return this.needsResolutionField;
            }
            set
            {
                this.needsResolutionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14")]
    public enum FileRevisionIterationAssociationType
    {

        /// <remarks/>
        Dependency,

        /// <remarks/>
        Attachment,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14")]
    public partial class FileRevisionIterationRef
    {

        private System.DateTime createDateField;

        private int checksumField;

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime CreateDate
        {
            get
            {
                return this.createDateField;
            }
            set
            {
                this.createDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Checksum
        {
            get
            {
                return this.checksumField;
            }
            set
            {
                this.checksumField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14")]
    public enum FileClassification
    {

        /// <remarks/>
        None,

        /// <remarks/>
        DesignVisualization,

        /// <remarks/>
        DesignDocument,

        /// <remarks/>
        ConfigurationMember,

        /// <remarks/>
        ConfigurationFactory,

        /// <remarks/>
        ElectricalProject,

        /// <remarks/>
        DesignSubstitute,

        /// <remarks/>
        DesignRepresentation,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14")]
    public enum FileACLbehavior
    {

        /// <remarks/>
        Override,

        /// <remarks/>
        Combined,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14", IsNullable = false)]
    public partial class Link
    {

        private UDP[] uDPField;

        private string targetIdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UDP")]
        public UDP[] UDP
        {
            get
            {
                return this.uDPField;
            }
            set
            {
                this.uDPField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "IDREF")]
        public string TargetId
        {
            get
            {
                return this.targetIdField;
            }
            set
            {
                this.targetIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.autodesk.com/pseb/dm/DataImport/2015-04-14", IsNullable = false)]
    public partial class ACL
    {

        private ACLACE[] aCEField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ACE")]
        public ACLACE[] ACE
        {
            get
            {
                return this.aCEField;
            }
            set
            {
                this.aCEField = value;
            }
        }
    }

}


