--Creation
IF NOT EXISTS(SELECT * FROM sys.columns WHERE[name] = N'Validation_Comment' AND[object_id] = OBJECT_ID(N'Folders')) BEGIN ALTER TABLE Folders ADD Validation_Comment varchar(max), Validation_Status varchar(20) END; 
IF NOT EXISTS(SELECT * FROM sys.columns  WHERE [name] = N'Validation_Comment' AND [object_id] = OBJECT_ID(N'Files')) BEGIN ALTER TABLE Files ADD Validation_Comment varchar(max), Validation_Status varchar(20) END;
IF NOT EXISTS(SELECT * FROM sys.columns  WHERE [name] = N'Validation_Comment' AND [object_id] = OBJECT_ID(N'FileFileRelations')) BEGIN ALTER TABLE FileFileRelations ADD Validation_Comment varchar(max), Validation_Status varchar(20) END;
--Updating
update Folders set Validation_Comment =concat('Duplicate folder. ',Validation_Comment), Validation_Status='Error' where Path in (select Path  from folders GROUP BY FolderName , Path  Having count(FolderName)>1);
update Files set Validation_Comment =concat('File data is missing. ',Validation_Comment),Validation_Status='Error' where FileID in (SELECT FileID FROM Files where LocalFullFileName is Null OR FileName is Null OR  Category is null OR Classification is Null OR Version is Null OR CreateUser is Null OR CreateDate is Null);
update Files set Validation_Comment=concat('CreateDate is not in ascending order. ',Validation_Comment),Validation_Status='Error' where FileId in (select f.FileID from Files f join Files fm on f.FileName=fm.FileName where f.Version < fm.Version and f.CreateDate> fm.CreateDate);
update Folders set Validation_Comment =concat('Folder data is missing. ',Validation_Comment),Validation_Status='Error' where FolderID in(select FolderID from Folders where FolderName is null Or  Category is null or CreateUser is null Or CreateDate is null or FolderID in (select FolderID from Folders where Path IS NULL and ParentFolderID IS NULL)) ;
update Folders set Validation_Comment =concat('An endless loop. ',Validation_Comment),Validation_Status='Error' where FolderId in(select p.FolderId from Folders c join Folders p on c.ParentFolderID=p.FolderID where p.ParentFolderID=c.FolderID);
update FileFileRelations set Validation_Comment=concat('Relation`s logic is false. ',Validation_Comment),Validation_Status='Error' where IsAttachment=IsDependency;
update FileFileRelations set  Validation_Comment=concat('RefId is not found. ',Validation_Comment),Validation_Status='Error' where ParentFileID in (select ParentFileID from FileFileRelations where IsDependency=1 and RefId is NULL) and ChildFileID in (select ChildFileID from FileFileRelations where IsDependency=1 and RefId is NULL);